### ISSUE TITLE
我用的swiper 里面拥塞scroll-view 我不知道这个插件怎么用？

### ISSUE THREAD

**Issue by iceCream0311** [luyimei/mina-pull-down-refresh#1]
有没有相应的例子呢

**Comment by luyimei** [comment]
@iceCream0311 我给加上一个scroll-view中使用的例子吧

**Comment by luyimei** [comment]
@iceCream0311 增加了在scroll-view中使用的例子；增加了在swiper+scroll-view中使用的例子。可以参考一下，其实都差不多的

**Comment by iceCream0311** [comment]
恩恩谢谢
